name: 'Setup Hugo Theme'
description: 'Setup the Hugo theme for exampleSite'

runs:
  using: "composite"
  steps:
    - name: Setup theme for exampleSite
      shell: bash
      run: |
        cd exampleSite
        mkdir -p themes
        
        # Remove existing theme directory if it exists
        if [ -d "themes/Tranquilpeak4000" ]; then
          rm -rf themes/Tranquilpeak4000
        fi
        
        # Create theme directory
        mkdir -p themes/Tranquilpeak4000
        
        # Copy theme files with error checking
        echo "Copying theme files..."
        cp -r ../layouts themes/Tranquilpeak4000/ || { echo "Failed to copy layouts"; exit 1; }
        cp -r ../assets themes/Tranquilpeak4000/ || { echo "Failed to copy assets"; exit 1; }
        cp -r ../static themes/Tranquilpeak4000/ || { echo "Failed to copy static"; exit 1; }
        cp -r ../archetypes themes/Tranquilpeak4000/ || { echo "Failed to copy archetypes"; exit 1; }
        cp -r ../i18n themes/Tranquilpeak4000/ || { echo "Failed to copy i18n"; exit 1; }
        cp ../theme.toml themes/Tranquilpeak4000/ || { echo "Failed to copy theme.toml"; exit 1; }
        
        # Validate theme structure
        echo "Validating theme structure..."
        for dir in layouts assets static archetypes i18n; do
          if [ ! -d "themes/Tranquilpeak4000/$dir" ]; then
            echo "❌ Missing required directory: $dir"
            exit 1
          fi
        done
        
        if [ ! -f "themes/Tranquilpeak4000/theme.toml" ]; then
          echo "❌ Missing theme.toml"
          exit 1
        fi
        
        echo "✅ Theme setup completed successfully" 