name: Generate Preview

on:
  pull_request:
    branches: [master, main]

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive

      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build theme assets
        run: npm run build

      - name: Setup theme for exampleSite
        uses: ./.github/actions/setup-theme

      - name: Build example site
        run: |
          cd exampleSite
          hugo --minify --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/pr-${{ github.event.number }}/"

      - name: Deploy to GitHub Pages
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exampleSite/public
          destination_dir: preview/pr-${{ github.event.number }}
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy preview for PR #${{ github.event.number }}"
          full_commit_message: "Deploy preview for PR #${{ github.event.number }}"

      - name: Comment PR with preview URL
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@v7
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        with:
          script: |
            const previewUrl = `https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/pr-${{ github.event.number }}/`;

            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('🚀 **Deploy preview ready!**')
            );

            const commentBody = `🚀 **Deploy preview ready!**

            🔗 **Preview URL:** ${previewUrl}

            📝 **Changes in this PR:**
            ${process.env.PR_TITLE}

            ⏰ **Preview will be available until PR is closed**

            ---
            *This preview was automatically generated by GitHub Actions*`;

            if (botComment) {
              await github.rest.issues.updateComment({
                comment_id: botComment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: commentBody
              });
            }

      - name: Comment PR for forks
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: actions/github-script@v7
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Build completed successfully!**
              
              📝 **Changes in this PR:**
              ${process.env.PR_TITLE}
              
              ⚠️ **Note:** Preview deployment is only available for PRs from the same repository.
              For forks, please check the build artifacts for the generated site.
              
              ---
              *This comment was automatically generated by GitHub Actions*`
            });

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: preview-build-${{ github.event.number }}
          path: exampleSite/public/
          retention-days: 30
