name: Lint and Quality Checks

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
      continue-on-error: true

    - name: Check for security vulnerabilities
      run: npm audit --audit-level=moderate
      continue-on-error: true

    - name: Validate theme.toml
      run: |
        if [ -f "theme.toml" ]; then
          echo "✅ theme.toml exists"
          cat theme.toml
        else
          echo "❌ theme.toml missing"
          exit 1
        fi

    - name: Check Hugo theme structure
      run: |
        required_dirs=("layouts" "static" "assets" "archetypes" "exampleSite")
        for dir in "${required_dirs[@]}"; do
          if [ -d "$dir" ]; then
            echo "✅ $dir directory exists"
          else
            echo "❌ $dir directory missing"
            exit 1
          fi
        done

    - name: Validate example site config
      run: |
        if [ -f "exampleSite/config.toml" ]; then
          echo "✅ exampleSite/config.toml exists"
          # Check for required fields
          if grep -q "theme = " exampleSite/config.toml; then
            echo "✅ theme configuration found"
          else
            echo "❌ theme configuration missing"
            exit 1
          fi
        else
          echo "❌ exampleSite/config.toml missing"
          exit 1
        fi 