name: Security Scan
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/actions/setup-node

      - name: Install dependencies
        uses: ./.github/actions/install-deps

      - name: Run npm audit
        run: |
          echo "🔍 Running npm audit..."
          npm audit --audit-level=moderate || {
            echo "⚠️ Security vulnerabilities found. Check the report above."
            echo "Run 'npm audit fix' to attempt automatic fixes."
            exit 1
          }

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

      - name: Check for secrets in code
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: ${{ github.sha }}
          extra_args: --only-verified

      - name: Run OWASP ZAP scan (if public repo)
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://your-site-url.com'  # Replace with actual URL
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a' 