name: Test E2E Base Workflow

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Type of E2E test to run'
        required: false
        default: 'e2e'
        type: choice
        options:
          - e2e
          - visual
          - all

jobs:
  test-e2e-basic:
    name: Test basic E2E setup
    uses: ./.github/workflows/_e2e-base.yml
    with:
      test-type: 'e2e'
      playwright-command: 'echo "Mock E2E test run - skipping actual Playwright execution for validation"'
      timeout-minutes: 10
      upload-artifacts: false
      browsers: 'chromium'

  test-e2e-visual:
    name: Test visual regression setup
    uses: ./.github/workflows/_e2e-base.yml
    with:
      test-type: 'visual'
      playwright-command: 'echo "Mock visual test run - skipping actual Playwright execution for validation"'
      timeout-minutes: 15
      upload-artifacts: true
      artifact-retention-days: 3
      browsers: 'chromium,firefox'

  test-e2e-all-browsers:
    name: Test all browsers setup
    uses: ./.github/workflows/_e2e-base.yml
    with:
      test-type: 'all'
      playwright-command: 'echo "Mock comprehensive test run - skipping actual Playwright execution for validation"'
      timeout-minutes: 20
      browsers: 'all'
      generate-report: true

  validate-e2e-results:
    name: Validate E2E Base Results
    runs-on: ubuntu-latest
    needs: [test-e2e-basic, test-e2e-visual, test-e2e-all-browsers]
    steps:
      - name: Validate test completion
        run: |
          echo "✅ All E2E base workflow tests completed successfully"
          echo "- Basic E2E test: completed"
          echo "- Visual regression test: completed"
          echo "- All browsers test: completed"
          echo ""
          echo "🔍 E2E base workflow validation passed"
          echo ""
          echo "⚠️ Note: These tests use mock Playwright commands to validate"
          echo "   workflow setup without running actual browser tests."